name: Deploy to Sakura Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.0
      with:
        host: laravel-times.sakura.ne.jp
        username: laravel-times
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/home/laravel-times/www/daily-calc-assistant"

    - name: Run deployment commands on server
      uses: appleboy/ssh-action@master
      with:
        host: laravel-times.sakura.ne.jp
        username: laravel-times
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/laravel-times/www/daily-calc-assistant
          git pull origin main
          composer install --no-dev
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
